version: "3"

services:
  app:
    hostname: app
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - .:/app
      - appdeps:/app/.venv:cached
    working_dir: /app
    tty: true

volumes:
  appdeps:
    driver: local
